### ISSUE TITLE
About "AFD" method GPU question

### ISSUE THREAD

**Issue by jerryold** [uuuChen/NTHU_LAB-Model-Compression-GraduallyAttentionDIstillation#2]
Hello, uuuChen

I was wondering about your AFD method, when I use gpu to train it. I faced the some problem like the following, but other method can work in gpu environment

### Bug return
**"RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)"**

Because I spent a lot of time to debugging, but it still doesn't work. Have you face the problem?? If you have free time to help me, I will be very grateful to you. Look forward to hearing from you asap, Thank you!! I apologize for the inconvenience if I brought it to you.

**Comment by uuuChen** [comment]
Hello, jerryold

Thank you for your report! The revised version has been committed (Fixed by @willy142857), and thank you for your attention!

**Comment by jerryold** [comment]
Hello uuuChen:

Thanks for your reply, but I faced the some bug problem. I have question about top1&top5 accuracy and loss in the tensorboardX, how can I let them become as the same as the train_acc(top1&top5) and test_acc(top1&top5) in the log.file. I would appreciate it if you can help me.
